<a href="https://colab.research.google.com/github/raghav-pant17/ANN_diabetes_prediction_model/blob/main/ANN_diabetes_pred_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np
import pandas as pd

In [67]:
data = pd.read_csv("/content/diabetes.csv")

In [68]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [69]:
data.shape

(768, 9)

In [70]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [71]:
data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [72]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [73]:
x = data.drop(["Outcome"], axis=1)
y = data["Outcome"]

In [74]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [75]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [76]:
x_train[:5]

array([[-1.17672157,  0.53266634, -1.50188775,  0.9435954 ,  0.78211699,
         1.41764156,  5.31938375,  0.00532207],
       [-0.57397224, -0.27360121, -0.46017862, -1.24974984, -0.67961113,
        -0.72583089, -0.38900199, -0.87053858],
       [ 0.63152643, -0.18057033, -3.585306  , -1.24974984, -0.67961113,
        -4.04884737, -0.840977  , -0.60778039],
       [ 0.93290109,  2.08318084, -0.04349497,  1.19426343,  1.96542071,
         0.73274504, -0.65020833,  0.70601059],
       [ 0.63152643,  0.9668104 , -0.35600771,  0.69292737,  0.36448038,
         0.45371312,  0.63527905, -0.43260826]])

In [77]:
x_train.shape

(576, 8)

In [78]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [79]:
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name='input_layer'), #input_layer has 8 neurons
    layers.Dense(16,activation='relu',name='hidden_layer_1'), #hidden_layer_1 has 16 neurons
    layers.Dense(32,activation='relu',name='hidden_layer_2'), #hidden_layer_2 has 32 neurons
    layers.Dense(1,activation='sigmoid',name='output_layer') #output_layer has just 1 neuron since it is a binary classifier
])

In [80]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [81]:
model.fit(x_train,y_train,epochs=15,batch_size=32)

Epoch 1/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5226 - loss: 0.6959
Epoch 2/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6910 - loss: 0.6372
Epoch 3/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7205 - loss: 0.5989
Epoch 4/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5704
Epoch 5/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7448 - loss: 0.5481
Epoch 6/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7569 - loss: 0.5299
Epoch 7/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.5156
Epoch 8/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7708 - loss: 0.5030
Epoch 9/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7656 - loss: 0.4940
Epoch 10/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7674 - loss: 0.4860
Epoch 11/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7778 - loss: 0.4794
Epoch 12/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7708 - loss: 0.4727
Epoch 13/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7778 - loss: 0.4689
Epoch 14/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7830 - loss: 0.4637
Epoch 15/15
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7847 - loss: 0.4611

In [82]:
y_pred=model.predict(x_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [84]:
y_pred = (y_pred > 0.5).astype(int)

In [85]:
accuracy=accuracy_score(y_test, y_pred)
print(accuracy)

0.7760416666666666

In [89]:
confusion_matrix(y_test, y_pred)
#                Predicted
#                  0    1
# Actual  0       TN   FP
# Acutual 1       FN   TP

#  100(TN) precited as non diabetic and they are also non diabetic
#  16(FP) predicted as diabetic but are actually non diabetic
#  27(FN) predicted as non diabetic but are actually diabetic
#  49(TP) predicted as diabetic and are also diabetic

array([[100,  16],
       [ 27,  49]])